### ISSUE TITLE
Eagle >DATE_TIME format

### ISSUE THREAD

**Issue by UweBonnes** [AislerHQ/aisler-support#10]
Hello,

while local eagle uses the german time format, Aisler rendering uses the american time format. This uses substantial more area and my coworkers can be fooled by e.g. 12/8/2021 vs 08.12.2021 (august vs december)
See attached JPG.
Please think about a better solution!

![aisler](https://user-images.githubusercontent.com/1142704/145194483-a5246832-a5d8-41b2-b213-0e8594db1a07.jpg)

**Comment by UweBonnes** [comment]
Yes. Look at eg. https://aisler.net/p/MATULCMD

**Comment by T-Krug** [comment]
This is unfortunately a no fix.  We have a server where the export happens automatically we cannot adjust it on a customer/location base.  

You can follow this Guide and create a Manufacturing Output that is also suitable for assembly locally thus your personal settings will be applied. https://community.aisler.net/t/exporting-a-custom-gerber-file-from-eagle/2309
