### ISSUE TITLE
Allow to choose "2 Layer Blitz" vs "2 Layer HD"

### ISSUE THREAD

**Issue by UweBonnes** [AislerHQ/aisler-support#12]
Hello,

it seems that for my last design, sized 320x35 mm, HD was choosen to guarantue good planarity. However the design (2021-28393) is mostly a mechanical one, with no SMD parts at all. I would love to have  in "Blitz" time and planarity is no issue for me. But there is no way to choose Blitz, even at own risk.

Bye

**Comment by PatrickFranken** [comment]
This rating is caused by the elongated holes on the design. Elongated holes are only available on the HD pool as it is time consuming to manufacture these.
