### ISSUE TITLE
Half laser name of design in stencils

### ISSUE THREAD

**Issue by UweBonnes** [AislerHQ/aisler-support#13]
It would be very helpfull if the name of the design would be visible on the stancil half-lasered!

**Comment by PatrickFranken** [comment]
Good point! It is probably not possible to do it half lasered as this would be to time consuming, however we will add it as cut-through text. I added an internal issue #138 to follow this request.

**Comment by UweBonnes** [comment]
I do not know is "half lasered" is the same as "angelasert" in https://www.multi-circuit-boards.eu/leiterplatten-design-hilfe/smd-schablonen.html. I meant "angelasert"

**Comment by PatrickFranken** [comment]
And exactly that "angelastert" is super time consuming why we would rather decide for cut -through as we do for the other text on the stencil. Anyway, I guess that is more of a minority. We will definitely add the project name.
