### ISSUE TITLE
Via Design Rules in KiCad outdated

### ISSUE THREAD

**Issue by MarcNue93** [AislerHQ/aisler-support#20]
I noticed that the via diameter and minimum drill holes got updated on Aisler Web Page and it does not correspond to the provided design rules in KiCad anymore.

For example: Minimum via diameter for complex board, Minimum annular ring, etc.
I think the minimum drill size for complex designes is still 0.1mm in the template.
![image](https://github.com/AislerHQ/aisler-support/assets/31733487/37e4095e-67d3-40d8-a897-2d528a098fda)

**Comment by Lithimlin** [comment]
It seems the design rules in general are outdated in this repo. The last update to the rules was just a few days ago, but the last update to this repo was months ago already
