### ISSUE TITLE
Altium Output Job doesn't produce Overlay (Legend) files.

### ISSUE THREAD

**Issue by orangelynx** [AislerHQ/aisler-support#7]
Title pretty much says all. Tested with Altium Designer 21.0.8. Can be easily enabled, but I feel this output job could use some revising.

**Comment by PatrickFranken** [comment]
Yes, the output job was pretty outdated. It'd be great if you could check the updated outjob including the Altium Publishing Destination. Have a look at https://aisler.community/t/altium-designer/90 for all details.
